config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :stories, only: [] do
      member do
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing # /users/pricing
      get :payment # /users/payment
      post :pay # /users/pay
    end
  end


  # /@emmastone/story_title
  get '@:username/:story_id', to: 'welcome#show', as: 'story_page'
  
  # /@emmastone
  get '@:username', to: 'welcome#user', as: 'user_page'

  get 'demo', to: 'welcome#demo'

  resources :stories do
    member do
      post :clap
    end
    resources :comments, only: [:create]
  end
end

app/views/shared/_flash.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_form.html.erb
<% if story.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <%= story.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for(story, html: { class: 'story-editor' }) do |f| %>
  <div class="form-group">
    <%= image_tag story.cover_image.variant(resize: '1000x800'), class: "cover-image" if story.cover_image.attached? %>
    <h3><%= f.label :cover_image %></h3>
    <%= f.file_field :cover_image, class: "form-control-file" %>
  </div>
  
  <div class="form-group">
    <h3><%= f.label :title %></h3>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <h3><%= f.label :content %></h3>
    <%= f.text_area :content, rows: 10, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <% if story.published? %>
      <%= f.submit :Renew, name: "save_as_draft", class: "btn btn-info" %>
    <% else %>
      <%= f.submit :Draft, name: "save_as_draft", class: "btn btn-info" %>
    <% end %>
    <%= f.submit :Publish, name: "publish", class: "btn btn-success" if story.may_publish? %>
    <%= f.submit :Unpublish, name: "unpublish", class: "btn btn-danger" if story.may_unpublish? %>
  </div>
  
<% end %>

<%= javascript_pack_tag 'editor' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "MediumWeb", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav ml-auto">
      <% if user_signed_in? %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <%= avatar(current_user, size: 50) %>
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Stories", stories_path, class: "dropdown-item" %>
            <%= link_to "New Story", new_story_path, class: "dropdown-item" %>
            
            <div class="dropdown-divider"></div>
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %> 
            <%= link_to "ProMember", pricing_users_path, class: "dropdown-item" unless current_user.paid_user? %> 
            
            <div class="dropdown-divider"></div>
            <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", 
                method: :delete, data: {confirm: "Are you sure？"} %>
          </div>
        </div>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %> 
        </li>
      <% end %>
    </ul>
  </div>
</nav>