config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :stories, only: [] do
      member do
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing # /users/pricing
      get :payment # /users/payment
      post :pay # /users/pay
    end
  end


  # /@emmastone/story_title
  get '@:username/:story_id', to: 'welcome#show', as: 'story_page'
  
  # /@emmastone
  get '@:username', to: 'welcome#user', as: 'user_page'

  get 'demo', to: 'welcome#demo'

  resources :stories do
    member do
      post :clap
    end
    resources :comments, only: [:create]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :find_story, only: [:show]
  def index
    # @stories = Story.order(created_at: :desc).includes(:user)
    # @stories = Story.where(status: 'published').order(created_at: :desc).includes(:user)
    # @stories = Story.published_stories.order(created_at: :desc).includes(:user)
    @stories = Story.published_stories
    @story = Story.order(clap: :desc).limit(4)
  end
  
  def show
    @comment = @story.comments.new
    @comments = @story.comments.order(id: :desc)
  end
  
  def user
    @user = User.find_by(username: params[:username])
  end
  
  private
  
  def find_story
    @story = Story.friendly.find(params[:story_id])
  end
end

app/views/welcome/_comment.html.erb
<section class="comment-content">
  <div class="comment">
    <div class="card border-white">
      <div class="card-body">
        <%= image_tag comment.user.avatar.variant(resize: '50x50'), class: "user-avatar" if comment.user.avatar.attached? %>
        <%= comment.user.username %>
        <p><%= simple_format(comment.content) %></p>
        <hr>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_comment_area.html.erb
<section class="comment-editor">
  <div class="comment-form">
    <% if user_signed_in? %>
      <%= form_with model: comment, url: story_comments_path(story), class: "comment_form", remote: true do |form| %>
        <div class="form-group">  
          <%= form.text_area :content, rows: 5, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.button 'Send', class: "btn btn-info" %>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/welcome/demo.html.erb
<div data-controller="demo">
  <input type="text" data-target="demo.content">
  <button data-action="click->demo#pushme">Push</button>
</div>

app/views/welcome/index.html.erb
<section>
  <div class="container">
    <!-- upper column -->
    <div class="row">
      <!-- upper left column -->
      <div class="col">

      </div>
      <!-- upper middle column -->
      <div class="col">

      </div>
      <!-- upper right column -->
      <div class="col">

      </div>
    </div>
    
    <hr>
    
    <!-- down column -->
    <div class="row">
      <!-- down left column -->
      <div class="col-lg-8 col-md-8 col-sm-12">
        <div class="card mb-3 border-white" style="max-width: 540px;">
          <% @stories.each do |story| %>  
            <div class="row no-gutters">
            
              <div class="col-md-10">
                <div class="card-body">
                  <h2 class="card-title"><%= link_to story.title, story_page_path(story.user.username, story), class: "text-dark text-decoration-none" %></h2>
                  <p class="card-text"><%= strip_tags(story.content).truncate(150) %></p>
                  <p class="card-text"><small class="text-muted">
                    <%= link_to story.user.username, user_page_path(story.user.username), class: "text-dark text-decoration-none" %> |
                    <%= story.updated_at.strftime('%F') %>
                  </small></p>
                </div>
              </div>

              <% if story.cover_image.attached? %>
                <div class="col-md-2">
                  <%= image_tag story.cover_image.variant(resize: '150X150'), class: "cover-image" %>
                </div>
              <% end %>

            </div>
            <hr>
          <% end %>
        </div>
      </div>
      <!-- down right column -->
      <div class="col-lg-4 col-md-4 col-sm-12">
        <!-- Followers stories -->
        <div class="col-12"></div>

        <!-- Popular Top 4 -->
        <div class="col-12">
          <h2>Popular on WebMedium</h2>
          <hr>
          <% @story.each do |story| %>
            <h2><%= link_to story.title, story_page_path(story.user, story), class: "text-decoration-none text-dark" %></h2>
            <small><p><%= link_to story.user.username, user_page_path(story.user.username), class: "text-decoration-none text-dark" %></p>
            <p class="text-muted"><%= story.updated_at.strftime("%F") %></p></small>
          <% end %>
        </div>

        <!-- My Bookmark Recently -->
        <div class="col-12">

        </div>
        <hr>
        <!-- Footer -->
        <div class="col-12 remove-spots">
          <ul>
            <li><%= link_to "Help", "#", class: "text-decoration-none text-secondary" %></li>
            <li><%= link_to "Status", "#", class: "text-decoration-none text-secondary" %></li>
            <li><%= link_to "Writers", "#", class: "text-decoration-none text-secondary" %></li>
            <li><%= link_to "Blog", "#", class: "text-decoration-none text-secondary" %></li>
            <li><%= link_to "Careers", "#", class: "text-decoration-none text-secondary" %></li>
            <li><%= link_to "Privacy", "#", class: "text-decoration-none text-secondary" %></li>
            <li><%= link_to "Terms", "#", class: "text-decoration-none text-secondary" %></li>
            <li><%= link_to "About", "#", class: "text-decoration-none text-secondary" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8">
      <h1 class="text-center"><%= @story.title %></h1>
      
      <span class="profile" data-controller="user">
        <%= avatar(@story.user, size: 50) %>
        <%= @story.user.username %>
        <%= link_to "#", class: "btn btn-secondary follow-button",
                         data: { action: "user#follow",
                                 user: @story.user.id, 
                                 target: "user.followButton" } do %>
          <%= (user_signed_in? && current_user.follow?(@story.user)) ? "Followed" : "Follow" %>
        <% end %>

        <%= link_to "#", class: "bookmark-button", 
                         data: { action: "user#addBookmark", 
                                 slug: @story.slug } do %>
          <% if user_signed_in? && current_user.bookmark?(@story) %>
            <i class="fas fa-bookmark bookmark-icon" data-target="user.bookmark"></i>
          <% else %>
            <i class="far fa-bookmark bookmark-icon" data-target="user.bookmark"></i>
          <% end %>
        <% end %>
      </span>
      
      <article class="content">
        <%= image_tag @story.cover_image.variant(resize: '1000x500'), class: 'cover-image' if @story.cover_image.attached? %>
        <p class="text-justify"><%= @story.content.html_safe %></p>
      </article>

      <footer data-controller="story">
        <%= link_to "#", class: "clapButton text-decoration-none", data: { action: "story#addClap", slug: @story.slug } do %>
          <i class="far fa-thumbs-up fa-2x"></i>
          <span data-target="story.clapCount" class="clapCount"><%= @story.clap %></span>
        <% end %>
      </footer>
      <hr>
    </div>  
  </div>
  <div class="row justify-content-md-center">
    <div class="col-6">
      <section class="comment">
        <h2>Comment</h2>
        <%= render "comment_area", story: @story, comment: @comment %>
        <%= render partial: "comment", collection: @comments %>
      </section>
    </div>
  </div>
</div>

app/views/welcome/user.html.erb
<section class="user-page">
  <div class="container">
    <!-- User Introduction -->
    <div class="row justify-content-md-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="row">
          <div class="col-lg-4 col-md-4 col-sm-12">
            <%= image_tag @user.avatar.variant(resize: "200x200"), class: "user-page-avatar" if @user.avatar.attached? %>
          </div>
          <div class="col-lg-8 col-md-8 col-sm-12">
            <span class="profile" data-controller="user">
              <h3>
                <%= @user.username %>
                <%= link_to "#", class: "btn btn-secondary follow-button",
                                      data: { action: "user#follow",
                                              user: @user.id, 
                                              target: "user.followButton" } do %>
                <%= (user_signed_in? && current_user.follow?(@user)) ? "Followed" : "Follow" %>
                <% end %>
              </h3>
            </span>
            <p class="text-muted"><%= simple_format(@user.intro) %></p>
            <p class="text-muted">
              <%= @user.followings.count %> Following
              <%= @user.followers.count %> Followers
            </p>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <!-- Story Lists -->
    <div class="row justify-content-md-center">
      <div class="col-lg-8 col-md-10 col-sm-12">

        <% @stories.each do |story| %>
          <%= link_to story_page_path(story.user.username, story), class: "text-decoration-none text-dark" do %>
            <div class="card mb-3">
              <div class="card-body">
                <p class="card-text">
                  <%= avatar(story.user) %>
                  <%= story.user.username %>
                  <p class="card-text"><small class="text-muted"><%= story.updated_at.strftime('%F') %></small></p>
                </p>
                <div class="container-sm container-md container-lg">
                  <%= image_tag story.cover_image, class: "card-img-top user-page-image" if story.cover_image.attached? %>
                </div>
                <h1 class="card-title"><%= story.title %></h1>
                <p class="card-text"><%= story.content.html_safe %></p>
              </div>

              
                <div class="row">
                  <!-- Clap -->
                  <article class="col-9 offset-1">
                    <span data-controller="story">
                      <%= link_to "#", class: "text-decoration-none text-muted",
                                        data: { action: "story#addClap",
                                                  slug: story.slug } do %>
                        <i class="far fa-thumbs-up"></i>
                        <span data-target="story.clapCount"><%= story.clap %></span>
                      <% end %>

                    </span>
                  </article>

                  <!-- Bookmark -->
                  <article class="col-2">
                    <span class="profile" data-controller="user">
                      <%= link_to "#", class: "bookmark-button text-decoration-none text-muted", 
                                        data: { action: "user#addBookmark", 
                                                  slug: story.slug } do %>
                        <% if user_signed_in? && current_user.bookmark?(story) %>
                          <i class="fas fa-bookmark" data-target="user.bookmark"></i>
                        <% else %>
                          <i class="far fa-bookmark" data-target="user.bookmark"></i>
                        <% end %>
                      <% end %>
                    </span>
                  </article>
                </div>
                
              
            </div>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</section>