config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :stories, only: [] do
      member do
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing # /users/pricing
      get :payment # /users/payment
      post :pay # /users/pay
    end
  end


  # /@emmastone/story_title
  get '@:username/:story_id', to: 'welcome#show', as: 'story_page'
  
  # /@emmastone
  get '@:username', to: 'welcome#user', as: 'user_page'

  get 'demo', to: 'welcome#demo'

  resources :stories do
    member do
      post :clap
    end
    resources :comments, only: [:create]
  end
end

app/models/story.rb
class Story < ApplicationRecord
  acts_as_paranoid
  
  extend FriendlyId
  friendly_id :slug_candidate, use: :slugged

  include AASM
  
  # relationships
  belongs_to :user
  has_one_attached :cover_image
  has_many :comments
  has_many :bookmarks

  # validations
  validates :title, presence: true

  # scope
  # default_scope { where(deleted_at: nil) }
  # scope :published_stories, -> { where( status: 'published' )}
  scope :published_stories, -> { published.with_attached_cover_image.order(created_at: :desc).includes(:user) }

  # instance methods
  # def destroy
    # update(deleted_at: Time.now)
  # end

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  # aasm
  aasm(column: 'status', no_direct_assignment: true) do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end
  end

  

  private

  def slug_candidate
    [
      :title,
      [:title, SecureRandom.hex[0, 8]]
    ]
  end
end

app/controllers/api/stories_controller.rb
class Api::StoriesController < Api::BaseController
  before_action :authenticate_user!
  before_action :find_story

  def clap
    @story.increment!(:clap)
    render json: { status: @story.clap }
  end

  def bookmark
    render json: { status: current_user.bookmark!(@story) }
  end
  
  private
  
  def find_story
    @story = Story.friendly.find(params[:id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_story, only: [:edit, :show, :update, :destroy]

  def index
    @stories = current_user.stories.order(created_at: :desc)
  end

  def new
    @story = current_user.stories.new
  end

  def create
    @story = current_user.stories.new(story_params)
    # @story.status = 'published' if params[:publish]
    @story.publish! if params[:publish]

    if @story.save
      if params[:publish]
        redirect_to stories_path, notice: "Story is publish!"
      else
        redirect_to edit_story_path(@story), notice: "Story is saved."
      end
    else
      render 'new', notice: "Something is in error."
    end
  end

  def update
    if @story.update(story_params)
      case
      when params[:publish]
        @story.publish!
        redirect_to stories_path, notice: "Story is published!"
      when params[:unpublish]
        @story.unpublish!
        redirect_to stories_path, notice: "Story is unpublished!"
      else
        redirect_to edit_story_path(@story), notice: "Story is saved now."
      end
    else
      render 'edit', notice: "Somthing is in error."
    end
  end

  def destroy
    @story.destroy
    redirect_to stories_path, notice: "Deleted successfully"
  end

  private
  
  def story_params
    params.require(:story).permit(:title, :content, :cover_image)
  end

  def find_story
    @story = current_user.stories.friendly.find(params[:id])
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-10">
      <h1>Edit Story</h1>
      <%= render 'shared/form', story: @story %>
    </div>
  </div>
</div>

app/views/stories/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-12">
      <h1>My Stories</h1>
      <hr>
      <% @stories.each do |story| %>
        <h2>
          <%= link_to story.title, edit_story_path(story), class: "text-dark text-decoration-none" %>
          <%= content_tag :span, 'Publish', class: "badge badge-secondary is-tag" if story.published? %>
        </h2>
        <p><%= strip_tags(story.content).truncate(200) %></p>
        <p>
          Last edited time:
          <% if Time.now - story.updated_at > 1.day %>
            <%= story.updated_at.strftime('%F') %>
          <% else %>
            <%= time_ago_in_words(story.updated_at) %>
          <% end %>
          <%= link_to "Edit", edit_story_path(story), class: "text-secondary" %>
          <%= link_to "Delete", story_path(story), method: :delete, class: "btn btn-sm btn-danger", 
              data: {confirm: "Are you sure?"} %>
        
        </p>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/stories/new.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8">
      <h1>Add New Story</h1>
      <%= render 'shared/form', story: @story %>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-10">
      <h1><%= @story.title %></h1>
      <p><%= @story.content %></p>
    </div>
  </div>
</div>